default:
  after_script:
    - date --iso-8601=seconds
  before_script:
    - date --iso-8601=seconds
  cache:
    key:
      files:
        - './go.mod'
        - './go.sum'
      prefix: "${CI_COMMIT_REF_SLUG}"
    paths:
      - './.go/'
      - './.go-build/'
    policy: pull-push
    when: on_success
  image:
    name: 'golang:1.14'
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
      - scheduler_failure
      - stuck_or_timeout_failure
  tags:
    - 'docker runner'
  timeout: 15 minutes

variables:
#  CI_DEBUG_TRACE: 'true'
  GIT_STRATEGY: fetch
  GIT_DEPTH: 10
  GOCACHE: "${CI_PROJECT_DIR}/.go-build/"
  GOPATH: "${CI_PROJECT_DIR}/.go/"

stages:
  - verify
  - build
  - deploy

check:
  script:
    - files="$(gofmt -l $(find ./ -path './.go*' -prune -o -type f -name '*.go' -print))"; test -z "${files}" || { echo "${files}"; false; }
    - go vet ./...
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.38.0
    - '"${GOPATH}/bin/golangci-lint" run -c golangci.yaml ./...'
    - go install 'github.com/kisielk/errcheck'
    - '"${GOPATH}/bin/errcheck" ./...'
  stage: verify

test:
  artifacts:
    expire_in: 1 week
    reports:
      junit: './report.xml'
    when: always
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[ci-skip-test]/
  script:
    - go install 'github.com/jstemmer/go-junit-report'
    - go test -v -race ./... 2>&1 | "${GOPATH}/bin/go-junit-report" -set-exit-code > './report.xml'
  stage: verify

build:
  artifacts:
    expire_in: 1 week
    name: "${CI_PROJECT_PATH_SLUG}-${CI_JOB_NAME}-${CI_PIPELINE_ID}-${CI_JOB_ID}-${CI_COMMIT_SHA}"
    paths:
      - './deploy/'
      - './resources/'
      - './reportengine'
    when: on_success
  script:
    - go build 'reportengine.go'
  stage: build

.deploy-template:
  artifacts:
    expire_in: 1 week
    name: "${CI_PROJECT_PATH_SLUG}-${CI_ENVIRONMENT_SLUG}-${CI_JOB_NAME}-${CI_PIPELINE_ID}-${CI_JOB_ID}-${CI_COMMIT_SHA}"
    paths:
      - './spbi-reportengine.tgz'
    when: always
  cache: {}
  environment:
    action: start
    name: "${ENVIRONMENT}"
    url: "${ENVIRONMENT_URL}"
  image:
    name: 'registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest'
  interruptible: false
  retry: 0
  script:
    - cp "${!CONFIG_BASE}" './base.env'
    - cp "${!CONFIG_REPORTENGINE}" './reportengine.env'
    - |
      [[ -v 'CERTIFICATE' ]] && cp "${!CERTIFICATE}" './certificate.pem' && certificate='./certificate.pem' || certificate=''
    - |
      [[ -v 'KEY' ]] && cp "${!KEY}" './key.pem' && certificate="${certificate} ./key.pem" || certificate=''
    - tar --create --file './spbi-reportengine.tgz' --gzip './base.env' './reportengine.env' './reportengine' './resources/' --directory "${CI_PROJECT_DIR}/deploy/aws/codedeploy/reportengine/" ./
    - aws s3 sync ./ "s3://${ARTIFACTS_BUCKET}/" --exclude '*' --include 'spbi-*' --delete
    - source './deploy/gitlab/deploy-to-ec2.bash'
    - deploy_to_ec2 "${ENVIRONMENT}" "${REVISION_BUCKET}" 'spbi-reportengine' "${CI_COMMIT_SHA}"
  timeout: 30 minutes
  variables:
    GIT_STRATEGY: none

deploy-production:
  allow_failure: false
  extends: .deploy-template
  only:
    refs:
      - 'release'
  resource_group: 'production'
  stage: deploy
  variables:
    ARTIFACTS_BUCKET: "${PRODUCTION_ARTIFACTS_BUCKET}"
    REVISION_BUCKET: "${PRODUCTION_REVISION_BUCKET}"
    AWS_ACCESS_KEY_ID: "${PRODUCTION_AWS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${PRODUCTION_AWS_KEY}"
    AWS_DEFAULT_REGION: "${PRODUCTION_AWS_REGION}"
    CONFIG_BASE: 'PRODUCTION_CONFIG_BASE'
    CONFIG_REPORTENGINE: 'PRODUCTION_CONFIG_REPORTENGINE'
    CERTIFICATE: 'PRODUCTION_CERTIFICATE'
    KEY: 'PRODUCTION_KEY'
    ENVIRONMENT: 'production'
    ENVIRONMENT_URL: "${PRODUCTION_ENVIRONMENT_URL}"
  when: manual
