#cloud-config

repo_update: true
repo_upgrade: all

apt:
  sources:
    google-chrome.list:
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1.4.2.2 (GNU/Linux)

        
        =Quqp
        -----END PGP PUBLIC KEY BLOCK-----
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        -----END PGP PUBLIC KEY BLOCK-----
      source: 'deb https://dl.google.com/linux/chrome/deb/ stable main'

swap:
  filename: '/swap'
  size: auto
  maxsize: 4294967296

packages:
  - 'google-chrome-stable'
  - 'ruby'
  - 'mysql-client-8.0'

runcmd:
  - "wget ''"
  - chmod +x './install'
  - mkdir '/run/runcmd/'
  - "'./install' auto > '/run/runcmd/codedeploy-install.log'"
  - service 'codedeploy-agent' status
